function ret = get_cov_reporttype(r)
%GET_COV_REPORTTYPE Summary of this function goes here
%   Detailed explanation goes here

ret = struct(...
        'm_id', r.m_id,...
        'skipped', r.skipped,...
        'opens', r.opens,...
        'timedout', false,...
        'simdur', [],...
        'exception', false,...
        'exception_msg', [],...
        'exception_ob', [],...
        'sys', r.sys,...
        'blocks', [],...
        'numzerocov', [],...
        'stoptime_changed', [],...
        'loc', [],... % Actual location. Inaccurate for EXPLORE 
        'loc_input', r.loc_input,... % model path which was provided as input.
        'duration', []);

end

