classdef ReportForModel < handle
    %REPORTFORMODEL Report for a single model from model collection
    %   One instance of this class is generated by one instance of
    %   emi.BaseModelMutator class
    
    properties
        exp_no;
        m_id;
        opens = [];
        exception = [];
        exception_id = [] ;
        mutants = [] ;
        exception_ob = [] ;
    end
    
    methods
        function obj = ReportForModel(exp_no, m_id)
            obj.exp_no = exp_no;
            obj.m_id = m_id;
        end
        
        function ret = get_report(obj)
            ret = utility.get_struct_from_object(obj);
        end
        
    end
    
end

