classdef ReportForModel < handle
    %REPORTFORMODEL Report for a single model from model collection
    %   One instance of this class is generated by one instance of
    %   emi.BaseModelMutator class
    
    properties
        exp_no;
        m_id;
        opens = [];
        exception = [];
        exception_id = [] ;
        mutants = [] ;
        exception_ob = [] ;
    end
    
    methods
        function obj = ReportForModel(exp_no, m_id)
            obj.exp_no = exp_no;
            obj.m_id = m_id;
        end
        
        function ret = get_report(obj)
            ret = utility.get_struct_from_object(obj);
        end
        
        function ret = is_ok(obj)
            % Note: not checking mutant results
            ret = true;
            
            if ~isempty(obj.exception) && obj.exception
                ret = false;
                return;
            end
        end
        
        function ret = are_mutants_ok(obj)
            ret = true;
            
            if isempty(obj.mutants)
                return;
            end
            
            ret = all(cellfun(@(p)isempty(p.exception),obj.mutants));
        end
        
    end
    
end

